### ISSUE TITLE
打开train、dev、text时报错

### ISSUE THREAD

**Issue by beagood** [luopeixiang/named_entity_recognition#1]
运行时出现打开文件问题
UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 2: illegal multibyte sequence
但因为对build_corpus函数不熟悉，不知道参数是什么，无法改成utf-8格式。
想咨询博主应该怎么办，谢谢回答！
如果方便的话，想请博主给我一个联系方式，或者通过邮箱联系。我的个人邮箱是384569486@qq.com。
再次感谢！

**Comment by luopeixiang** [comment]
你好，我在linux下面用python3运行的时候没有此问题,请问你使用的python版本是2还是3呢？

**Comment by luopeixiang** [comment]
> 运行时出现打开文件问题
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 2: illegal multibyte sequence
> 但因为对build_corpus函数不熟悉，不知道参数是什么，无法改成utf-8格式。
> 想咨询博主应该怎么办，谢谢回答！
> 如果方便的话，想请博主给我一个联系方式，或者通过邮箱联系。我的个人邮箱是[384569486@qq.com](mailto:384569486@qq.com)。
> 再次感谢！

你好，我在linux下面用python3运行的时候没有此问题,请问你使用的python版本是2还是3呢？

**Comment by beagood** [comment]
您好，我是在windows下面用的python3.7版本，编译器用的是pycharm。

**Comment by luopeixiang** [comment]
UnicodeDecodeError这个问题已经通过更新[data.py](https://github.com/luopeixiang/named_entity_recognition/blob/master/data.py)中的open函数解决

**Comment by beagood** [comment]
已解决，谢谢！

**Comment by xuqiankun1104** [comment]
> 已解决，谢谢！如何解决的，可以细说一下嘛！谢谢
