### ISSUE TITLE
ResumeNER数据好像有点小问题哦

### ISSUE THREAD

**Issue by chaoyueziji** [luopeixiang/named_entity_recognition#15]
传上来repo的ResumeNER数据有点问题，运行的时候data.py 第16行会报错，大概是有空行的原因，我用了原作者的就不会出现这个问题。（环境啥的都没问题，应该就是上传的那份数据存在一个空行）
再次感谢大佬开源鸭。。。

**Comment by dengxuanxiang** [comment]
是的，我也发现了

**Comment by dengxuanxiang** [comment]
你是怎么解决的

**Comment by chaoyueziji** [comment]
> 你是怎么解决的
去官网重新下载数据就解决了

**Comment by chaoyueziji** [comment]
> 你是怎么解决的

官网下载数据

**Comment by Zhenguoshen** [comment]
line!='\r\n'
那个换句识别逻辑改成这样就OK了，不用重新下数据

**Comment by chaoyueziji** [comment]
> line!='\r\n'
> 那个换句识别逻辑改成这样就OK了，不用重新下数据

好的~~~
