### ISSUE TITLE
关于HMM解码时初始状态计算的问题

### ISSUE THREAD

**Issue by Zessay** [luopeixiang/named_entity_recognition#3]
你好，在models中的HMM解码那部分，计算序列首元素的标签概率的时候，直接将初始状态概率Pi和元素对应的标签概率bt相加，这样概率和不就不为1了吗？希望能帮忙解答一下，谢谢！

**Comment by luopeixiang** [comment]
相加是在对数空间相加的，
log(p1) + log(p2) = log(p1 × p2)
实际上是两个概率相乘之后的对数，不会等于1.

**Comment by Zessay** [comment]
不知道是不是我理解有问题，我的意思是，对于首元素，应该要保证它属于所有标签的概率和为1的，比如说首元素的状态有t_1, t_2, ..., t_n中可能，应该有t_1 + t_2 + .. + t_n = 1；但是这里如果直接把对数概率相加的话，好像没办法保证概率和为1。非常感谢你的回复，还望指教一下！

**Comment by luopeixiang** [comment]
![t](https://user-images.githubusercontent.com/16150164/56014644-b9df3980-5d28-11e9-8d32-d55de96340bc.png)

**Comment by Zessay** [comment]
好的，明白了，感谢这些详细的回复！
