### ISSUE TITLE
打开ckpts中训练好的模型出错

### ISSUE THREAD

**Issue by Zessay** [luopeixiang/named_entity_recognition#4]
你好，我用pickle.load()打开训练好的模型，报了No module named 'models.hmm'这样的错误，所有的模型都会出错，请问一下这是为什么呢？

**Comment by luopeixiang** [comment]
pcikle模块说找不到models.hmm，可能是工作目录的问题，你试一下在将工作目录切换到项目目录下加载。

**Comment by Zessay** [comment]
感谢，已解决！
