### ISSUE TITLE
环境配置不成功

### ISSUE THREAD

**Issue by AnitaSherry** [luopeixiang/named_entity_recognition#45]
发现错误
AttributeError: 'LSTM' object has no attribute '_flat_weights'
搜索后发现是torch版本问题，我用的是最新版本1.11.0
想要更换版本发现1.0.1.post2不存在
ERROR: Could not find a version that satisfies the requirement torch==1.0.1.post2 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.0.1.post2
搜索后发现window不支持
随后在服务器上安装
发现依旧不支持，所以这个项目无法进行下去了

**Comment by pustar** [comment]
同样的问题，装了好多遍，装好之后进行测试时一直提示
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
装的就是requirements中提到的torch的版本
Pytorch version：1.0.1.post2

**Comment by EstrellaXiao** [comment]
我也遇到了这个问题，请问有解决方案了吗？

**Comment by EstrellaXiao** [comment]
用这个应该能行：conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

**Comment by AnitaSherry** [comment]
5年前老掉牙的东西了，还看这干啥
